# Generated by Django 2.1.2 on 2018-11-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='faward',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='festival',
            name='faward1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='festival',
            name='fgenre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='festival',
            name='fhelder',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='fhomepage',
            field=models.TextField(null=True),
        ),
    ]
